version: 2

models: 
  - name: stg_transactions
    description: Transaction in the Eth Blockchain
    columns:
      - name: hash
        description: >
          This is very long description of hash key
          which is multiline
        data_tests:
          - unique
          - not_null
