version: 2

models: 
  - name: stg_transactions
    description: Transaction in the Eth Blockchain
    columns:
      - name: hash
        description: >
          This is very long description of hash key
          which is multiline
        data_tests:
          - unique
          - not_null
          - relationships:
              to: ref('stg_token_transfers')
              field: transaction_hash
              severity: warn
              config:
                store_failures: true
                store_failures_as: table
                where: date > current_date - 30

  - name: stablecoin_activity_per_day
    # latest_version: 1
    config:
      contract:
        enforced: true
    columns:
      - name: date
        data_type: date
        description: ""

      - name: token_address
        data_type: varchar
        description: ""

      - name: type
        data_type: varchar
        description: ""
        data_tests:
          - accepted_values:
              values: ['Hybrid', 'Crypto-backed', 'Fiat-backed']

      - name: symbol
        data_type: varchar
        description: ""

      - name: total_usd_value
        data_type: float
        description: ""

  - name: stg_transactions_enriched
    description: Enriched transaction data with token information
    columns:
      - name: value
        data_tests:
          - generic_test_positive_value:
              field: block_number




unit_tests:
  - name: test_is_valid_transaction_category
    description: "Test to validate the transaction category based on token symbol and type"
    model: stg_transactions_enriched
    overrides:
      macros:
        # unit test this model in "full refresh" mode
        is_incremental: false 
    given:
      - input: ref('stg_transactions')
        rows:
          - {receipt_contract_address: 'Om'}
      - input: ref('stg_token_transfers')
        rows:
          - {transaction_hash: 'bla'}
    expect:
      rows:
        - {transaction_category: 'contract_creation'}



    # versions:
    
    #   - v: 1
    #     deprecation_date: 2026-06-30
    #     # Matches what's above -- nothing more needed
    
    #   - v: 2
    #     # Removed a column -- this is the breaking change!
    #     columns:
    #       # This means: use the 'columns' list from above, but exclude country_name
    #       - include: all
    #         exclude: [symbol, token_address]